server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store_db
    username: postgres
    password: JennyLovesPizza

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true

  web:
    resources:
      add-mappings: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true